name: Check cc/c++
description: Check cc/c++ (on Cygwin)
runs:
  using: composite
  steps:
    # Is this really the most stable piece of `gcc --version` output?
    - run: |
        check_tool() {
            local exe
            for exe; do
                output="$( "$exe" --version )"
                echo "$output"
                if ! echo "$output" | grep -F -- "This is free software; see the source for copying conditions."; then
                    echo 'Unexpected `'"$exe"' --version` output.' >&2
                    exit 1
                fi
            done
        }
        check_tool cc
        check_tool c++
      shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
