name: Install GCC
description: Install GCC

inputs:
  version:
    description: GCC version to install
    required: false
    default: latest
  platform:
    description: Target platform
    required: false
    default: x64
  cygwin:
    description: Install Cygwin packages
    required: false
    default: 0
  cc:
    description: Set up cc/gcc/c++/g++ executables
    required: false
    default: 1
  hardlinks:
    description: On Cygwin, replace executable symlinks with hardlinks
    required: false
    default: 0

outputs:
  gcc:
    description: gcc binary name
    value: '${{ steps.install.outputs.gcc }}'
  gxx:
    description: g++ binary name
    value: '${{ steps.install.outputs.gxx }}'

runs:
  using: composite
  steps:

    - if: ${{ runner.os == 'Linux' && inputs.version == '4.4' }}
      shell: bash
      run: |
        sudo apt-get update
        mkdir install-gcc-${{ inputs.version }}
        cd install-gcc-${{ inputs.version }}
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.4/g++-4.4_4.4.7-8ubuntu1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.4/libstdc++6-4.4-dev_4.4.7-8ubuntu1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.4/gcc-4.4-base_4.4.7-8ubuntu1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.4/gcc-4.4_4.4.7-8ubuntu1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.4/cpp-4.4_4.4.7-8ubuntu1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.4/gcc-4.4-multilib_4.4.7-8ubuntu1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/main/g/gcc-10/lib32gcc1_10.5.0-1ubuntu1~20.04_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/main/m/mpfr4/libmpfr4_3.1.2-1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/main/g/glibc/multiarch-support_2.27-3ubuntu1.6_amd64.deb
        sudo apt-get install ./g++-4.4_4.4.7-8ubuntu1_amd64.deb ./libstdc++6-4.4-dev_4.4.7-8ubuntu1_amd64.deb ./gcc-4.4-base_4.4.7-8ubuntu1_amd64.deb ./gcc-4.4_4.4.7-8ubuntu1_amd64.deb ./cpp-4.4_4.4.7-8ubuntu1_amd64.deb ./gcc-4.4-multilib_4.4.7-8ubuntu1_amd64.deb ./lib32gcc1_10.5.0-1ubuntu1~20.04_amd64.deb ./libmpfr4_3.1.2-1_amd64.deb ./multiarch-support_2.27-3ubuntu1.6_amd64.deb

    - if: ${{ runner.os == 'Linux' && inputs.version == '4.6' }}
      shell: bash
      run: |
        sudo apt-get update
        mkdir install-gcc-${{ inputs.version }}
        cd install-gcc-${{ inputs.version }}
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.6/g++-4.6_4.6.4-6ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.6/libstdc++6-4.6-dev_4.6.4-6ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.6/gcc-4.6-base_4.6.4-6ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.6/gcc-4.6_4.6.4-6ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.6/cpp-4.6_4.6.4-6ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.6/gcc-4.6-multilib_4.6.4-6ubuntu2_amd64.deb
        wget http://archive.ubuntu.com/ubuntu/pool/main/g/gcc-10/lib32gcc1_10.5.0-1ubuntu1~20.04_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/main/m/mpfr4/libmpfr4_3.1.2-1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/main/g/glibc/multiarch-support_2.27-3ubuntu1.6_amd64.deb
        sudo apt-get install ./g++-4.6_4.6.4-6ubuntu2_amd64.deb ./libstdc++6-4.6-dev_4.6.4-6ubuntu2_amd64.deb ./gcc-4.6-base_4.6.4-6ubuntu2_amd64.deb ./gcc-4.6_4.6.4-6ubuntu2_amd64.deb ./cpp-4.6_4.6.4-6ubuntu2_amd64.deb ./gcc-4.6-multilib_4.6.4-6ubuntu2_amd64.deb ./lib32gcc1_10.5.0-1ubuntu1~20.04_amd64.deb ./libmpfr4_3.1.2-1_amd64.deb ./multiarch-support_2.27-3ubuntu1.6_amd64.deb

    - if: ${{ runner.os == 'Linux' && inputs.version == '4.8' }}
      shell: bash
      run: |
        sudo apt-get update
        mkdir install-gcc-${{ inputs.version }}
        cd install-gcc-${{ inputs.version }}
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.8/g++-4.8_4.8.5-4ubuntu8_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.8/libstdc++-4.8-dev_4.8.5-4ubuntu8_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.8/gcc-4.8-base_4.8.5-4ubuntu8_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.8/gcc-4.8_4.8.5-4ubuntu8_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.8/libgcc-4.8-dev_4.8.5-4ubuntu8_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.8/cpp-4.8_4.8.5-4ubuntu8_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.8/libasan0_4.8.5-4ubuntu8_amd64.deb
        sudo apt-get install ./gcc-4.8_4.8.5-4ubuntu8_amd64.deb ./gcc-4.8-base_4.8.5-4ubuntu8_amd64.deb ./libstdc++-4.8-dev_4.8.5-4ubuntu8_amd64.deb ./cpp-4.8_4.8.5-4ubuntu8_amd64.deb ./libgcc-4.8-dev_4.8.5-4ubuntu8_amd64.deb ./libasan0_4.8.5-4ubuntu8_amd64.deb ./g++-4.8_4.8.5-4ubuntu8_amd64.deb

    - if: ${{ runner.os == 'Linux' && inputs.version == '5' }}
      shell: bash
      run: |
        sudo apt-get update
        mkdir install-gcc-${{ inputs.version }}
        cd install-gcc-${{ inputs.version }}
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-5/g++-5_5.5.0-12ubuntu1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-5/libstdc++-5-dev_5.5.0-12ubuntu1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-5/gcc-5-base_5.5.0-12ubuntu1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-5/gcc-5_5.5.0-12ubuntu1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-5/libgcc-5-dev_5.5.0-12ubuntu1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-5/cpp-5_5.5.0-12ubuntu1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-5/libasan2_5.5.0-12ubuntu1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-7/libubsan0_7.5.0-6ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-7/libcilkrts5_7.5.0-6ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-7/gcc-7-base_7.5.0-6ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/i/isl-0.18/libisl15_0.18-4_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-5/libmpx0_5.5.0-12ubuntu1_amd64.deb
        sudo apt-get install ./gcc-5_5.5.0-12ubuntu1_amd64.deb ./gcc-5-base_5.5.0-12ubuntu1_amd64.deb ./libstdc++-5-dev_5.5.0-12ubuntu1_amd64.deb ./cpp-5_5.5.0-12ubuntu1_amd64.deb ./libgcc-5-dev_5.5.0-12ubuntu1_amd64.deb ./libasan2_5.5.0-12ubuntu1_amd64.deb ./g++-5_5.5.0-12ubuntu1_amd64.deb ./libubsan0_7.5.0-6ubuntu2_amd64.deb ./libcilkrts5_7.5.0-6ubuntu2_amd64.deb ./gcc-7-base_7.5.0-6ubuntu2_amd64.deb ./libisl15_0.18-4_amd64.deb ./libmpx0_5.5.0-12ubuntu1_amd64.deb

    - if: ${{ runner.os == 'Linux' && inputs.version == '6' }}
      shell: bash
      run: |
        sudo apt-get update
        mkdir install-gcc-${{ inputs.version }}
        cd install-gcc-${{ inputs.version }}
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-6/g++-6_6.4.0-17ubuntu1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-6/libstdc++-6-dev_6.4.0-17ubuntu1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-6/gcc-6-base_6.4.0-17ubuntu1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-6/gcc-6_6.4.0-17ubuntu1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-6/libgcc-6-dev_6.4.0-17ubuntu1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-6/cpp-6_6.4.0-17ubuntu1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-6/libasan3_6.4.0-17ubuntu1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-7/gcc-7-base_7.5.0-6ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-7/libubsan0_7.5.0-6ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-7/libcilkrts5_7.5.0-6ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/main/i/isl/libisl19_0.19-1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/main/i/isl/libisl22_0.22.1-1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/main/g/gcc-8/gcc-8-base_8.4.0-1ubuntu1~18.04_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/main/g/gcc-8/libmpx2_8.4.0-1ubuntu1~18.04_amd64.deb
        sudo apt-get install ./g++-6_6.4.0-17ubuntu1_amd64.deb ./libstdc++-6-dev_6.4.0-17ubuntu1_amd64.deb ./gcc-6-base_6.4.0-17ubuntu1_amd64.deb ./gcc-6_6.4.0-17ubuntu1_amd64.deb ./libgcc-6-dev_6.4.0-17ubuntu1_amd64.deb ./cpp-6_6.4.0-17ubuntu1_amd64.deb ./libasan3_6.4.0-17ubuntu1_amd64.deb ./gcc-7-base_7.5.0-6ubuntu2_amd64.deb ./libubsan0_7.5.0-6ubuntu2_amd64.deb ./libcilkrts5_7.5.0-6ubuntu2_amd64.deb ./libisl19_0.19-1_amd64.deb ./gcc-8-base_8.4.0-1ubuntu1~18.04_amd64.deb ./libmpx2_8.4.0-1ubuntu1~18.04_amd64.deb

    - if: ${{ runner.os == 'Linux' && inputs.version == '7' }}
      shell: bash
      run: |
        sudo apt-get update
        mkdir install-gcc-${{ inputs.version }}
        cd install-gcc-${{ inputs.version }}
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-7/g++-7_7.5.0-6ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-7/libstdc++-7-dev_7.5.0-6ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-7/gcc-7-base_7.5.0-6ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-7/gcc-7_7.5.0-6ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-7/libgcc-7-dev_7.5.0-6ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-7/cpp-7_7.5.0-6ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-7/libasan4_7.5.0-6ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-7/libubsan0_7.5.0-6ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-7/libcilkrts5_7.5.0-6ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-7/gcc-7-base_7.5.0-6ubuntu2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/main/i/isl/libisl22_0.22.1-1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/main/g/gcc-8/gcc-8-base_8.4.0-1ubuntu1~18.04_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/main/g/gcc-8/libmpx2_8.4.0-1ubuntu1~18.04_amd64.deb
        sudo apt-get install ./g++-7_7.5.0-6ubuntu2_amd64.deb ./libstdc++-7-dev_7.5.0-6ubuntu2_amd64.deb ./gcc-7-base_7.5.0-6ubuntu2_amd64.deb ./gcc-7_7.5.0-6ubuntu2_amd64.deb ./libgcc-7-dev_7.5.0-6ubuntu2_amd64.deb ./cpp-7_7.5.0-6ubuntu2_amd64.deb ./libasan4_7.5.0-6ubuntu2_amd64.deb ./libubsan0_7.5.0-6ubuntu2_amd64.deb ./libcilkrts5_7.5.0-6ubuntu2_amd64.deb ./gcc-7-base_7.5.0-6ubuntu2_amd64.deb ./libisl22_0.22.1-1_amd64.deb ./gcc-8-base_8.4.0-1ubuntu1~18.04_amd64.deb ./libmpx2_8.4.0-1ubuntu1~18.04_amd64.deb

    # Cannot find the required dependencies
    - if: false # ${{ runner.os == 'Linux' && inputs.version == '8' }}
      shell: bash
      run: |
        sudo apt-get update
        mkdir install-gcc-${{ inputs.version }}
        cd install-gcc-${{ inputs.version }}
        wget https://old-releases.ubuntu.com/ubuntu/pool/universe/g/gcc-8/g++-8_8.4.0-7ubuntu3_amd64.deb
        wget https://old-releases.ubuntu.com/ubuntu/pool/universe/g/gcc-8/libstdc++-8-dev_8.4.0-7ubuntu3_amd64.deb
        wget https://old-releases.ubuntu.com/ubuntu/pool/universe/g/gcc-8/gcc-8-base_8.4.0-7ubuntu3_amd64.deb
        wget https://old-releases.ubuntu.com/ubuntu/pool/universe/g/gcc-8/gcc-8_8.4.0-7ubuntu3_amd64.deb
        wget https://old-releases.ubuntu.com/ubuntu/pool/universe/g/gcc-8/libgcc-8-dev_8.4.0-7ubuntu3_amd64.deb
        wget https://old-releases.ubuntu.com/ubuntu/pool/universe/g/gcc-8/cpp-8_8.4.0-7ubuntu3_amd64.deb
        wget http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6_2.35-0ubuntu3_amd64.deb
        # Cannot find version 8.4.0 of libubsan1
        wget https://old-releases.ubuntu.com/ubuntu/pool/universe/g/gcc-8/libubsan1-dbg_8.2.0-7ubuntu1_amd64.deb
        wget https://old-releases.ubuntu.com/ubuntu/pool/universe/g/gcc-8/libmpx2_8.4.0-7ubuntu3_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/main/i/isl/libisl22_0.22.1-1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/main/i/isl/libisl23_0.26-3_amd64.deb
        sudo apt-get install ./g++-8_8.4.0-7ubuntu3_amd64.deb ./libstdc++-8-dev_8.4.0-7ubuntu3_amd64.deb ./gcc-8-base_8.4.0-7ubuntu3_amd64.deb ./gcc-8_8.4.0-7ubuntu3_amd64.deb ./libgcc-8-dev_8.4.0-7ubuntu3_amd64.deb ./cpp-8_8.4.0-7ubuntu3_amd64.deb ./libc6_2.35-0ubuntu3_amd64.deb ./libubsan1-dbg_8.2.0-7ubuntu1_amd64.deb ./libmpx2_8.4.0-7ubuntu3_amd64.deb ./libisl22_0.22.1-1_amd64.deb ./libisl23_0.26-3_amd64.deb

    - if: ${{ ! (inputs.version <= 7) }}
      id: install
      run: |
        New-Variable os -Value '${{ runner.os }}' -Option Constant

        New-Variable linux_host -Value ($os -eq 'Linux') -Option Constant
        New-Variable cygwin_host -Value ('${{ inputs.cygwin }}' -eq '1') -Option Constant
        New-Variable windows_host -Value ($os -eq 'Windows' -and !$cygwin_host) -Option Constant

        New-Variable version -Value ('${{ inputs.version }}') -Option Constant
        New-Variable latest -Value ($version -eq 'latest') -Option Constant
        New-Variable x64 -Value ('${{ inputs.platform }}' -eq 'x64') -Option Constant

        function Locate-Choco {
            $path = Get-Command 'choco' -ErrorAction SilentlyContinue
            if ($path) {
                $path.Path
            } else {
                Join-Path ${env:ProgramData} 'chocolatey' 'bin' 'choco'
            }
        }

        function Enable-TestingPPA {
            sudo add-apt-repository --yes --update ppa:ubuntu-toolchain-r/test
        }

        function Install-Package {
            param(
                [Parameter(Mandatory=$true, ValueFromRemainingArguments=$true)]
                [string[]] $Packages
            )

            if ($script:linux_host) {
                $VERSION_ID = (echo 'source /etc/os-release; echo "$VERSION_ID"' | bash)
                sudo apt-get update
                sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends $Packages
            } elseif ($script:cygwin_host) {
                $choco = Locate-Choco
                & $choco install $Packages -y --no-progress --source=cygwin
            } elseif ($script:windows_host) {
                $choco = Locate-Choco
                & $choco upgrade $Packages -y --no-progress --allow-downgrade
            } else {
                throw "Sorry, installing packages is unsupported on $script:os"
            }
        }

        if ($linux_host) {
            $pkg = 'g++'
            $gcc = 'gcc'
            $gxx = 'g++'
            if (!$latest) {
                $pkg += "-$version"
                $gcc += "-$version"
                $gxx += "-$version"
                Enable-TestingPPA
            }
            if (!$x64) {
                $pkg += '-multilib'
            }
            Install-Package $pkg
        } elseif ($cygwin_host) {
            if (!$x64) {
                echo @'
        ::warning ::
        32-bit-targeting GCC is unstable and/or unmaintained on 64-bit Cygwin.
        Please use 32-bit Cygwin instead.
        If you _are_ using 32-bit Cygwin, you can ignore this message.
        '@
            }

            $pkg = 'gcc-g++'
            $gcc = 'gcc'
            $gxx = 'g++'

            Install-Package $pkg
        } elseif ($windows_host) {
            # TODO: use setup-mingw when calling composite actions within
            # composite actions is implemented.
            echo @'
        ::error ::
        Please use the egor-tensin/setup-mingw action to install GCC on Windows.
        '@
            exit 1
        } else {
            throw "Sorry, installing GCC is unsupported on $os"
        }

        echo "gcc=$gcc" >> $env:GITHUB_OUTPUT
        echo "gxx=$gxx" >> $env:GITHUB_OUTPUT
      shell: pwsh

    - if: ${{ ! (inputs.version <= 8) }}
      run: |
        New-Variable os -Value '${{ runner.os }}' -Option Constant

        New-Variable linux_host -Value ($os -eq 'Linux') -Option Constant
        New-Variable cygwin_host -Value ('${{ inputs.cygwin }}' -eq '1') -Option Constant
        New-Variable windows_host -Value ($os -eq 'Windows' -and !$cygwin_host) -Option Constant

        New-Variable cc -Value ('${{ inputs.cc }}' -eq '1') -Option Constant

        New-Variable gcc -Value '${{ steps.install.outputs.gcc }}' -Option Constant
        New-Variable gxx -Value '${{ steps.install.outputs.gxx }}' -Option Constant

        function Link-Exe {
            param(
                [Parameter(Mandatory=$true)]
                [string] $Exe,
                [Parameter(Mandatory=$true)]
                [string] $LinkName
            )

            $exe_path = (Get-Command $Exe).Path
            $link_dir = if ($script:windows_host) { Split-Path $exe_path } else { '/usr/local/bin' }
            $link_name = if ($script:windows_host) { "$LinkName.exe" } else { $LinkName }
            $link_path = if ($script:cygwin_host) { "$link_dir/$link_name" } else { Join-Path $link_dir $link_name }
            echo "Creating link $link_path -> $exe_path"
            if ($script:linux_host) {
                sudo ln -f -s $exe_path $link_path
            } elseif ($script:cygwin_host) {
                ln.exe -f -s $exe_path $link_path
            } elseif ($script:windows_host) {
                New-Item -ItemType HardLink -Path $link_path -Value $exe_path -Force | Out-Null
            }
        }

        if ($cc) {
            Link-Exe $gcc cc
            if ($gcc -ne 'gcc') {
                Link-Exe $gcc 'gcc'
            }
            Link-Exe $gxx c++
            if ($gxx -ne 'g++') {
                Link-Exe $gxx 'g++'
            }
        }
      shell: pwsh

    - if: ${{ ! (inputs.version <= 8) }}
      run: |
        New-Variable cygwin_host -Value ('${{ inputs.cygwin }}' -eq '1') -Option Constant
        New-Variable hardlinks -Value ('${{ inputs.hardlinks }}' -eq '1') -Option Constant

        if ($cygwin_host -and $hardlinks) {
            echo @'
        while IFS= read -d '' -r link_path; do
            dest_path="$( readlink --canonicalize-existing -- "$link_path" )"
            dest_ext=".${dest_path##*.}"
            [ "$dest_ext" == ".$dest_path" ] && dest_ext=
            link_ext=".${link_path##*.}"
            [ "$link_ext" == ".$link_path" ] && link_ext=
            echo "Removing symlink $link_path" && rm -f -- "$link_path"
            [ "$link_ext" != "$dest_ext" ] && echo "${PATHEXT//\;/
        }" | grep -q --ignore-case --line-regexp -F -- "$dest_ext" && link_path="$link_path$dest_ext"
            echo "Creating hardlink $link_path -> $dest_path" && ln -- "$dest_path" "$link_path"
        done < <( find /usr/local/bin /usr/bin \
                       -type l '-(' \
                       -path /usr/local/bin/cc -o \
                       -path /usr/local/bin/c++ \
                       '-)' -print0 )
        '@ | & bash.exe --login -o errexit -o nounset -o pipefail -o igncr
        }
      shell: pwsh

branding:
  icon: star
  color: green
