name: Run foo.exe
description: Run foo.exe and verify its output
runs:
  using: composite
  steps:
    - run: |
        $expected = @"
        Doing something #1
        Doing something #2
        Doing something #3
        "@

        $actual = & (Join-Path . foo)
        $actual = $actual -join [Environment]::NewLine

        $($actual -eq $expected) -or $(throw @"
        Unexpected output:
        $actual
        "@)
      shell: pwsh
