name: Test

on:
  push:
  pull_request:
  schedule:
    # Weekly, at 5:45 AM on Friday (somewhat randomly chosen).
    - cron: '45 5 * * 5'
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [x86, x64]
        cygwin: [0, 1]
        os: [ubuntu-18.04, windows-2019]

        include:
          # Prettier run names.
          - {os: ubuntu-18.04, name: Ubuntu}
          - {cygwin: 1, name: Cygwin}
        exclude:
          # No Cygwin on Ubuntu.
          - {os: ubuntu-18.04, cygwin: 1}
          # This action is not suitable for Windows hosts, use setup-mingw for
          # that.
          - {os: windows-2019, cygwin: 0}

    runs-on: '${{ matrix.os }}'

    name: '${{ matrix.name }} / ${{ matrix.platform }}'

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clean up PATH
        uses: egor-tensin/cleanup-path@v1
        if: runner.os == 'Windows'

      - name: Install Cygwin
        uses: egor-tensin/setup-cygwin@master
        with:
          platform: '${{ matrix.platform }}'
        if: matrix.cygwin

      - name: Set up GCC
        uses: ./
        with:
          platform: '${{ matrix.platform }}'
          cygwin: '${{ matrix.cygwin }}'

      - name: Build foo.exe
        run: |
          $flags = @()
          if ('${{ matrix.platform }}' -eq 'x86') {
              $flags += '-m32'
          }
          $flags += @(
              '-std=c++14',
              '-o', 'foo',
              'foo.cpp'
          )
          if ('${{ runner.os }}' -eq 'Linux') {
              $flags += '-lpthread'
          }
          g++ $flags

      - name: Run foo.exe
        run: |
          $expected = @"
          Doing something #1
          Doing something #2
          Doing something #3
          "@
          $actual = & (Join-Path . foo)
          $actual = $actual -join [Environment]::NewLine
          $($actual -eq $expected) -or $(throw @"
          Unexpected output:
          $actual
          "@)

      # Is this really the most stable piece of `gcc --version` output?
      - name: Check cc/c++
        run: |
          $cc = & cc --version
          echo $cc
          $($cc | Select-String -Pattern "This is free software; see the source for copying conditions." -SimpleMatch -Quiet) -or $(throw "Unexpected `cc --version` output")
          $cxx = & c++ --version
          echo $cxx
          $($cxx | Select-String -Pattern "This is free software; see the source for copying conditions." -SimpleMatch -Quiet) -or $(throw "Unexpected `c++ --version` output")
